/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_shone_testjni_HelloWorld */

#ifndef _Included_com_shone_testjni_HelloWorld
#define _Included_com_shone_testjni_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_shone_testjni_HelloWorld
 * Method:    printJNI
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_shone_testjni_HelloWorld_printJNI
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
